services:
  langfuse-web:
    image: langfuse/langfuse:3@sha256:50fcca2e82289d1eeafb3edc16af4da0c30e04ecf12d106eb707165057f1c8b3
    environment:
      DATABASE_URL: ${LANGFUSE_DATABASE_URL}
      REDIS_CONNECTION_STRING: ${LANGFUSE_REDIS_URL}
      CLICKHOUSE_URL: ${LANGFUSE_CLICKHOUSE_URL}
      CLICKHOUSE_USER: ${LANGFUSE_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${LANGFUSE_CLICKHOUSE_PASSWORD}
      NEXTAUTH_SECRET: ${LANGFUSE_NEXTAUTH_SECRET}
      SALT: ${LANGFUSE_SALT}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  langfuse-worker:
    image: langfuse/langfuse-worker:3@sha256:53a0828a63e71dce6b700ffd784d871ad7e64c4dd7d2614606f6683b70d62962
    environment:
      DATABASE_URL: ${LANGFUSE_DATABASE_URL}
      REDIS_CONNECTION_STRING: ${LANGFUSE_REDIS_URL}
      CLICKHOUSE_URL: ${LANGFUSE_CLICKHOUSE_URL}
      CLICKHOUSE_USER: ${LANGFUSE_CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${LANGFUSE_CLICKHOUSE_PASSWORD}
      SALT: ${LANGFUSE_SALT}
    restart: unless-stopped
