"""StrongClaw hypermemory engine and CLI."""

from clawops.hypermemory.cli import main, parse_args
from clawops.hypermemory.config import default_config_path, load_config
from clawops.hypermemory.engine import HypermemoryEngine
from clawops.hypermemory.models import (
    BackendConfig,
    CompatibleHttpRerankConfig,
    CorpusPathConfig,
    DenseSearchCandidate,
    EmbeddingConfig,
    GovernanceConfig,
    HybridConfig,
    HypermemoryConfig,
    IndexedDocument,
    InjectionConfig,
    LocalSentenceTransformersRerankConfig,
    ParsedItem,
    ProposalRecord,
    QdrantConfig,
    RankingConfig,
    ReflectionSummary,
    ReindexSummary,
    RerankConfig,
    RerankResponse,
    SearchBackend,
    SearchExplanation,
    SearchHit,
    SparseSearchCandidate,
)

__all__ = [
    "BackendConfig",
    "CompatibleHttpRerankConfig",
    "CorpusPathConfig",
    "DenseSearchCandidate",
    "EmbeddingConfig",
    "GovernanceConfig",
    "HybridConfig",
    "InjectionConfig",
    "IndexedDocument",
    "HypermemoryConfig",
    "HypermemoryEngine",
    "LocalSentenceTransformersRerankConfig",
    "ParsedItem",
    "ProposalRecord",
    "QdrantConfig",
    "RankingConfig",
    "RerankConfig",
    "RerankResponse",
    "ReflectionSummary",
    "ReindexSummary",
    "SearchExplanation",
    "SearchBackend",
    "SearchHit",
    "default_config_path",
    "load_config",
    "main",
    "parse_args",
    "SparseSearchCandidate",
]
